### PR TITLE
Pascal support

### PR DESCRIPTION
**Pull request by Fedor-Lyanguzov**
Hello again, Richard.

This pull request is about adding Pascal language support to Jobe server.

This is my first attempt at participation in open source development, so please be forgiving. I'm starting this pull request very early to make a place for conversation.

The goal is to make Pascal questions work as much like C-program questions as possible.

I see my development plan as:
1) Choose an open source Pascal compiler.
2) Add a task to jobe/application/libraries.
3) Make a test submit (in testsubmit.py?)

The choice of compiler is from:
1) [GNU Pascal](http://www.gnu-pascal.de/gpc/h-index.html)
2) [Free Pascal](http://www.freepascal.org/)
I have chosen Free Pascal because it has a live community, and i have some experience using it. I have installed it with:
```sudo apt-get install fp-compiler```
[Debian Wheezy 7.8 fp-compiler package](https://packages.debian.org/wheezy/fp-compiler-2.6.0)
Note: i see no reason in installing `fpc`(full package), because it has an IDE in it, while only compiler will be used.

I have created language task for Pascal based on c_task.php. While modifying it, i was stopped by a question, which i can't answer myself (even with Google). What is the meaning of `-lm` flag of gcc (c_task.php, line 35)?
```$cmd = "gcc " . implode(' ', $compileargs) . " -o $execFileName $src -lm 2>$errorFileName";```
I have only one idea: it's a `-l` link library flag, with `m` library. 

On a side note, how should i create a CodeRunner Pascal-program question, with Moodle interface or just by copying and editing c_program prototype in built-in protos?

Sincerely yours,
Fedor

### CODE REVIEW

**Comment by trampgeek** [comment]
Hi Fedor

Welcome aboard. I haven't had that much experience of open source 
collaborative development myself, so we'll both be learning as we go.

Your development plan sounds good.

Your guess about -lm was right. It's an option that gcc passes on to the 
link-editor ld, telling it to search the math library, libm.so (or 
equivalent) for unresolved references (e.g. for sqrt). I don't think it 
will be relevant to Pascal.

My preferred way to create a new prototype is to just create a new 
CodeRunner question of any type, then click Customize, open the Advanced 
Customisation panel, set the question to be a prototype /making sure to 
specify the new question type there/, and set up the required language 
and templates. Duplicating an existing prototype is also possible but 
again you have to make absolutely sure that you change the question type 
or you'll finish up with two prototypes for the same question type and 
all questions of that type will then crash (until you fix the prototype 
duplication).

Thanks again for participating.

Richard

**Comment by Fedor-Lyanguzov** [comment]
Hello, Richard.

I have written good and fail tests (one of each). Both tests gives reasonable outcome. Is there any particular tests, which i should implement? 

Note for merging: changed DEBUGGING to True and TEST_LANG to 'pascal', should revert to False and 'ALL' before merging.

Fedor

**Comment by trampgeek** [comment]
Hi Fedor

This sounds like good progress. However, I'm afraid I'm tied up all this week with work plus family matters. I hope to try a merge next week some time.

RIchard

**Comment by Fedor-Lyanguzov** [comment]
Hello, Richard.

I've made last changes: reverted DEBUGGING to false and TEST_LANG to ALL, added language_id and compile_args to language table in README.md. I think we're ready to merge.

Fedor

**Comment by trampgeek** [comment]
Hi Fedor

Thanks again for integrating Pascal into Jobe. Nice to have that. I've 
just updated the README to call this version 1.3 and acknowledged your 
contribution.

Hope all goes well with CodeRunner. I assume you now have a prototype 
question for Pascal too?

BTW, I recently pushed out a couple of CodeRunner bug fixes related to 
question export which were pretty important. The most recent one is 
essential if you're going to export prototypes.

Regards

Richard

**Comment by Fedor-Lyanguzov** [comment]
Hello, Richard

Thank you for your cooperation. It was really nice experience for me to work with you on open source project. I think i'll continue to participate in development of CodeRunner and Jobe, so i'm looking forward to work with you.

Today i have installed CodeRunner and Jobe on "production" servers, updated to recent version and created sample quiz, along with 100+ questions, for my colleagues. All went well, my boss was excited.

About prototype for CodeRunner, how should i add it to source? Add to CR_PROTOTYPES category, export this category and place Moodle XML file into some directory?

For now, i'm thinking about making little changes to devinstall script, to make it possible to install, while moodle is installed in directory other, than `/var/www` or something. I'll make pull request, when i will be ready.

Fedor

**Comment by Fedor-Lyanguzov** [comment]
Oh, i forgot to add `fp-compiler` package to install script. Please, put it right after `python3-pip` package.

**Comment by trampgeek** [comment]
Hi Fedor

It's great to have you aboard and I'm delighted that you're interested 
in continuing to participate in CodeRunner/Jobe development.

I'm most impressed that you've already got 100+ questions. That sounds 
like a massive effort. Did you write them all yourself or did you find 
some way to import them from elsewhere?

To add the Pascal prototype to CodeRunner, your suggestion is more or 
less correct. The exported CR_PROTOTYPES question xml file becomes 
CodeRunner/type/coderunner/db/builtin_PROTOTYPES.xml, which is then 
imported during the install.

I like the sound of your change to the install script(s). Someone else 
had trouble with the restriction to the /var/www file tree.

Regarding your follow up email - I already added the extra line to the 
install instructions and pushed it to github.

Regards

Richard

**Pull request merged**
