### PR TITLE
Moved completely to python3 and pylint3

### PR DESCRIPTION
**Pull request by garthwilliamson**
I changed some (hopefully all?) of the references to python to python3, and changed to using pylint3. This means it works out of the box in a fresh ubuntu 16.04 docker image.

### CODE REVIEW

**Comment by trampgeek** [comment]
Hi Garth

Thanks for this. I'm on holiday at present without a computer so can't do much right now. Will get onto it by the new year at the latest.

I wasn't aware the installer didn't work out of the box with an Ubuntu 16.04 docker image. I thought it worked out of the box with a freshly installed "standard" Ubuntu 16.04 from the web, so I'm curious to know exactly what broke. The installer used to work with either python2 or python3; did I break something recently?

One thing about your change that worries me: what will happen if someone tries installing on a Linux version that doesn't have python3, such as (I think) Centos? Centos installs seem rather common because some uni IT departments have a policy of always using Centos for security reasons.

Thanks again for the contribution. I would certainly like Jobe to work out of the box with the docker image, but I also wish to maintain compatibility with as many other Linux versions as possible.

Richard

**Comment by trampgeek** [comment]
Thanks Garth. Sorry about the delay in getting on to this. Changes all look good. I've decided that I can't be bothered supporting systems that don't have python3.

**Comment by garthwilliamson** [comment]
Hi Richard,
Sorry I missed your earlier communications about this. I'm not very experienced in Centos but if people complain get hold of me and I'll have a go at documenting how to install there.

G

**Comment by trampgeek** [comment]
That's a very generous offer. Thanks Garth.

**Pull request merged**
